services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: pomodoro
    volumes:
      - db_data:/var/lib/postgresql/data

  cache:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache_data:/data

  rabbitmq-test:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db_data:
    driver: local
  cache_data:
    driver: local
