"""username-nullable-for-google-ouath21

Revision ID: 0ea4974626cf
Revises: 9ce830be7636
Create Date: 2025-01-14 19:23:15.384527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ea4974626cf'
down_revision: Union[str, None] = '9ce830be7636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
