"""username-nullable-for-google-ouath22

Revision ID: 9ce830be7636
Revises: 4c91f31ef992
Create Date: 2025-01-12 14:39:47.600573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ce830be7636'
down_revision: Union[str, None] = '4c91f31ef992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
